# Glossary {#glossary}

Aviation is chock-a-block with acronyms. A good place to look for these is in [AIRIAL](https://www.eurocontrol.int/airial). The language of aviation and aviation statistics is also quite precise, though in practice people might say 'flight' when they strictly mean 'flight segment'. There is an elderly [EUROCONTROL glossary of statistics](TBD) and a more recent [Eurostat one](https://ec.europa.eu/eurostat/web/products-manuals-and-guidelines/-/ks-gq-19-004). This glossary chapter is deliberately chooses more hand-waving definitions, over the strictly water-tight.

Airport Data ('NM' v 'APT')
: In the EUROCONTROL airport data you might see that there are two counts of flights. One comes from the Network Manager (NM), the other direct from the airport (APT). While both are for 'IFR' flights (check [AIRIAL](https://www.eurocontrol.int/airial)), these counts are sometimes different. For example, look at Amsterdam Schiphol (EHAM). The airport reports on commercial flights, which means some non-commercial flights (by state aircraft, perhaps) are not included, which is why the totals from the two sources are slightly different. Neither is incorrect, they just serve slightly different purposes.

Open Data
: We use this in a broad sense, to include data that is available for free for non-commercial use. It might not be free for onward distribution. You might need to ask for a logon to get access to it.
