--- 
title: "Picturing Flights with R   UNDER CONSTRUCTION"
subtitle: "Exploring open data with open software"
author: "David Marsh"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
geometry: margin=3cm
description: "This book explores both open sources of aviation data and how to use the open tools of R and RStudio to understand that data. It's intended as a training course and guidebook, with exercises and pointers to more information along the way.  --- UNDER CONSTRUCTION ---"
---

# How to use this book {#howto}
--- UNDER CONSTRUCTION! ---

There's a growing range of freely-available data on aviation, covering flight patterns, airport locations, aircraft emissions, delays and whole lot more. You would be hard pushed to find anything similar for walking, road, rail or maritime, making aviation an exceptionally open mode of transport to explore, research and analyse. However, it can be a problem knowing where to start. Visualising the data that you have found is often a good way to begin to understand what you might be able to do with it. 

The [open-source software R](https://cran.r-project.org) provides a powerful set of functions for analysis and visualisation. [RStudio](https://posit.co/download/rstudio-desktop/) makes it easy to use R well. They're both free to download. As with the data, it can be hard to find your way around R, because sometimes it seems that there are a dozen ways to do anything. 

This book introduces both the aviation data and R, explaining through simple, but real examples. It aims to help you build a small but useful set of tools and data sources.

In the first chapters, we take some first steps in R, using aviation examples and with an emphasis on making graphs of the data. In later chapters, we move on to data analysis and more complex topics in mapping and text analysis.

## Before you start

You need to have [RStudio and R](https://posit.co/download/rstudio-desktop/#download) installed on your machine.


This book is available as [html here](https://david6marsh.github.io/flights_in_R/) and can be downloaded complete with data from here (TBD).

Air transport and air traffic management, like any domain, have their own jargon. This isn't a training book for air transport, but we will explain some key ideas along the way. Check out the glossary in chapter \@ref(glossary).

There are plenty of useful 'cheat sheets' for R, I'll introduce my favourites as we go through.

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```


## Ways to Use the Material

The book aims to support you using it in a number of different ways:

* Training. Work through chapters in order, or pick out specific chapters if you need a refresher on a topic (an R topic, or an aviation topic). Read the explanations, grab the code and run it, and test your understanding by answering questions [in square brackets in the text] and doing exercises.
* Reference. Use the book search (top left of this page) to find some how-to material directly.
* Snippets. The book builds up snippets of usable code (TBD - how complete?) for you to cut-and-paste.

But it is never going to replace the huge amount of excellent information, especially in [stackoverflow](https://stackoverflow.com/). A key principle is that _"Google is your friend"_: even if I prefer [DuckDuckGo](https://www.duckduckgo.com) for many purposes, a Google search is often more productive for R. Whether it's for how to do something, or how to respond to an error, usually someone has already suffered, and some kind person has helped them. Google it.

## Structure of the book

* Chapters \@ref(howto) and \@ref(start) should get you up and running in RStudio.
* Chapters \@ref(firstLook) to \@ref(sortbars) start with how to look at data, using a data viewer and with some initial graphs. If you're mostly using existing code that creates simple charts, written by someone else, then these chapters should help you find your way around, and start to adapt the code for your own needs.
* Chapters \@ref(loopsfunctions) (and TBD) do more data loading and wrangling, covering the basics of loops and functions
* more...TBD
* Chapter \@ref(maps) introduces the map functions in R, including where to find airspace structure data, and how to plot both great circle routes and actual route flown.
* Chapter \@ref(splitparse) covers pulling data out of strings (parsing) using 'regular expressions', with NOTAMs as the application.

## Acknowledgements

This book has partly been written whilst at [Eurocontrol](www.eurocontrol.int) and partly during a visiting research fellowship at Manchester Metropolitan University. Thanks to colleagues in both organisations for their ideas and patience. Any views expressed are entirely unofficial.

## What's gone wrong?

Learning from mistakes is essential, so each chapter has a "what's gone wrong?" section near the end, discussing some typical potholes that we all fall into from time to time. Look there, especially if you don't see the results from the code in the book that you were expecting.

We start the book with one classic pitfall: R is *case sensitive*, which can be quite a culture shock if you've been brought up on other systems. This matters for filenames as well as code. When in doubt, check whether you've got the right mix of upper- and lower-case letters! Or avoid the problem by using the little helpers in R Studio, such as the 'tab' key for completing filenames.

